spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: e-commerce-product-api
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password:
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


